### ISSUE TITLE
Cambiar intereses

### ISSUE THREAD

**Issue by fedebrasburg** [LinkUpFiuba/frontend#27]
Cambiar "men" por "male" y "women" por "female"

**Comment by AndresOtero** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix male y female como generos en el usuario](https://trello.com/c/4qRrxydf/24-fix-male-y-female-como-generos-en-el-usuario)

**Comment by AndresOtero** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix male y female como generos en el usuario](https://trello.com/c/4qRrxydf/24-fix-male-y-female-como-generos-en-el-usuario)
